#name: Deploy files to Airflow bucket
#on:
#  push:
#    branches: 
#      - '*'
#  pull_request:
#    branches:
#      - main
#      - qa
#      - develop
#jobs:
#  copy_to_s3:
#    runs-on: ubuntu-latest
#    env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_DEFAULT_REGION: ${{ secrets.ZONE }}
#  
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        
#      - name: Configurar Credenciales AWS
#        run: aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ env.AWS_DEFAULT_REGION }}
#  
#
#      - name: Copy DAGS into the Airflow Bucket
#        run: |
#          aws s3 sync dags s3://${{ secrets.BUCKET_NAME }}/dags/
#